### ISSUE TITLE
Change relative path to absolute

### ISSUE THREAD

**Issue by vinhali** [rafal-szypulka/itm_exporter#5]
Hello, why when I change the line

https://github.com/rafal-szypulka/itm_exporter/blob/74c9b849d5d819558f137c3bec872f059649f46c/main.go#L331

to

`yamlFile, err := ioutil.ReadFile("/etc/itm_exporter/config.yaml")`

Is the exporter unable to display all the parameters that exist in the `.YAML` file?

**Comment by rafal-szypulka** [comment]
Support for custom config file name and location added in version 0.6: https://github.com/rafal-szypulka/itm_exporter/releases/tag/v0.6
Use `-c /path/to/configfile.yaml`

**Comment by vinhali** [comment]
Very good, thanks a lot!
