### ISSUE TITLE
Scrapes have super long runtimes

### ISSUE THREAD

**Issue by ruohki** [rafal-szypulka/itm_exporter#6]
At some point the ITM API seems to significantly slow down, the scraping and the request to /metrics take moer than a minute with the default config and around 3 managed systems. Eventually the portal server freezes as well. Any idea?

/metrics sample
```
itm_scrape_duration_seconds{group="NTMEMORY"} 59.202864944
itm_scrape_duration_seconds{group="WTSYSTEM"} 59.197552453
```

```
- name: "WTSYSTEM"
  datasets_uri: "/providers/itm.TEMS/datasources/TMSAgent.%25IBM.STATIC021/datasets"
  labels: ["ORIGINNODE"]
  metrics: ["PCTTLPCSRT","PCTTLPRIVT","PCTTLUSERT","SYSUPDAYS"]
  managed_system_group: "*NT_SYSTEM"
- name: "NTMEMORY"
  datasets_uri: "/providers/itm.TEMS/datasources/TMSAgent.%25IBM.STATIC021/datasets"
  labels: ["ORIGINNODE"]
  metrics: ["AVAILBTMEM","COMMBYTE", "TOTMEMBYTE","CACHEBTS","MEMUPCT","AVAILPCT","CACHEPCT"]
  managed_system_group: "*NT_SYSTEM"
```

**Comment by rafal-szypulka** [comment]
Hi, try to increase TEPS heap size: https://www.ibm.com/support/pages/resolving-teps-ewas-memory-issues-increasing-jvm-heap-size (especially if you find OOM errors in the TEPS eWAS logs).

**Comment by ruohki** [comment]
The machine is a 4 core 8g ram rhel 8. I did increase the heap to 2gb and run into this issue - there is not really something that is being monitored yet - but from the itm_scrape_duration_seconds i think the Windows OS agent might be a bottleneck here for some reason.

I also use the other datasource you provide at the same time

**Comment by ruohki** [comment]
To finish this of i think the issue is related with the grafana-apm-datasource. After some quries the system locks up and the teps api cant be queried anymore. Heap is fine

**Comment by ruohki** [comment]
Okay - turns out the issue is not the plugin or the teps ... *drumroll* the nt agent is absolute garbage and ramps up cpu load to 50% after 1-2 queries.
